tool_id: infra.oracle_request_volume
g1: infra
description: Counts oracle requests per receiver over time.
g2: oracle
g3: oracle_request_volume
g4: Oracle Requests Daily
g5: Input sig filter
scope: generic
returns:
- name: day
  type: date
- name: receiver
  type: string
- name: requests
  type: number
inputs:
- key: oracle_sig
  type: text
  label: Function Sig
  default: '0x40429946'
  required: true
- key: date_from
  type: date
  label: Start Date
  required: false
