tool_id: infra.trace_error_rate
g1: infra
g2: gas
g3: trace_error_rate
g4: Failed Traces %
g5: Ethereum Traces
description: Calculates percentage of failed traces by period.
scope: generic
returns:
- name: year
  type: number
- name: error_percentage
  type: number
inputs:
- key: date
  label: Date
  type: date_range
  required: false
