tool_id: infra.bridge_deposit_volume
g1: infra
description: Aggregates daily ETH deposits and unique depositors to bridges.
g2: bridge
g3: bridge_deposit_volume
g4: Bridge Deposits
g5: Ethereum Transactions
scope: protocol:zkSync
returns:
- name: day
  type: date
- name: eth_deposited
  type: number
- name: unique_depositors
  type: number
inputs:
- key: protocol
  type: text
  label: Protocol
  default: zkSync
  required: true
- key: pool_address
  type: address
  label: Pool Address
  default: '0x32400084C286CF3E17e7B677ea9583e60a000324'
  required: true
