tool_id: infra.active_addresses_timeseries
g1: infra
description: Counts unique addresses sending or receiving transactions.
g2: wallet
g3: active_addresses_timeseries
g4: Active Addresses
g5: Ethereum Transactions
scope: generic
returns:
- name: time
  type: timestamp
- name: active_accounts
  type: number
inputs:
- key: date_from
  type: date
  label: Start Date
  required: false
